agentica-org/deepcoder-14b-preview:free
alibaba/tongyi-deepresearch-30b-a3b:free
arliai/qwq-32b-arliai-rpr-v1:free
cognitivecomputations/dolphin-mistral-24b-venice-edition:free
cognitivecomputations/dolphin3.0-mistral-24b:free
deepseek/deepseek-chat-v3-0324:free
deepseek/deepseek-chat-v3.1:free
deepseek/deepseek-r1-0528-qwen3-8b:free
deepseek/deepseek-r1-0528:free
deepseek/deepseek-r1-distill-llama-70b:free
deepseek/deepseek-r1:free
google/gemini-2.0-flash-exp:free
google/gemma-2-9b-it:free
google/gemma-3-12b-it:free
google/gemma-3-27b-it:free
google/gemma-3-4b-it:free
google/gemma-3n-e2b-it:free
google/gemma-3n-e4b-it:free
meituan/longcat-flash-chat:free
meta-llama/llama-3.2-3b-instruct:free
meta-llama/llama-3.3-70b-instruct:free
meta-llama/llama-3.3-8b-instruct:free
meta-llama/llama-4-maverick:free
meta-llama/llama-4-scout:free
microsoft/mai-ds-r1:free
mistralai/devstral-small-2505:free
mistralai/mistral-7b-instruct:free
mistralai/mistral-nemo:free
mistralai/mistral-small-24b-instruct-2501:free
mistralai/mistral-small-3.1-24b-instruct:free
mistralai/mistral-small-3.2-24b-instruct:free
moonshotai/kimi-dev-72b:free
moonshotai/kimi-k2:free
nousresearch/deephermes-3-llama-3-8b-preview:free
nvidia/nemotron-nano-9b-v2:free
openai/gpt-oss-20b:free
qwen/qwen-2.5-72b-instruct:free
qwen/qwen-2.5-coder-32b-instruct:free
qwen/qwen2.5-vl-32b-instruct:free
qwen/qwen2.5-vl-72b-instruct:free
qwen/qwen3-14b:free
qwen/qwen3-235b-a22b:free
qwen/qwen3-30b-a3b:free
qwen/qwen3-4b:free
qwen/qwen3-8b:free
qwen/qwen3-coder:free
shisa-ai/shisa-v2-llama3.3-70b:free
tencent/hunyuan-a13b-instruct:free
tngtech/deepseek-r1t-chimera:free
tngtech/deepseek-r1t2-chimera:free
z-ai/glm-4.5-air:free
